services:
  mongodb:
    image: mongo:7.0
    container_name: controlling-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - controlling-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: controlling-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - controlling-network

  metabase:
    build: .
    container_name: controlling-metabase
    restart: unless-stopped
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_FILE: ${MB_DB_FILE}
      JAVA_TIMEZONE: ${JAVA_TIMEZONE}
      MB_JETTY_HOST: ${MB_JETTY_HOST}
      MB_JETTY_PORT: ${MB_JETTY_PORT}
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/app/data
    depends_on:
      - mongodb
    networks:
      - controlling-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mongodb_data:
    driver: local
  metabase_data:
    driver: local

networks:
  controlling-network:
    driver: bridge